steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudrunproject-270900/github.com/ibarra17/ric-project:$SHORT_SHA', '.']
 - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudrunproject-270900/github.com/ibarra17/ric-project:$SHORT_SHA']
 
