steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ric-project/ric-project:$SHORT_SHA', '.']
 - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ric-project/ric-project:$SHORT_SHA']
 
